# Generated by Django 5.2.5 on 2025-09-01 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='market.owner'),
        ),
    ]
