# Generated by Django 5.2.5 on 2025-09-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_productmessage_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'CartItem', 'verbose_name_plural': 'CartItems'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ('Product',), 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcomments',
            options={'verbose_name': 'ProductComment', 'verbose_name_plural': 'ProductComments'},
        ),
        migrations.AlterModelOptions(
            name='productmessage',
            options={'verbose_name': 'ProductMessage', 'verbose_name_plural': 'ProductMessages'},
        ),
        migrations.AddField(
            model_name='productcomments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
