# Generated by Django 5.2.5 on 2025-09-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_productmessage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='market.productmessage'),
        ),
    ]
