# Generated by Django 5.2.5 on 2025-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_product_created_at_product_updated_at_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttobeower',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
