# Generated by Django 5.2.5 on 2025-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('general_enquiry', 'general_enquiry'), ('product_support', 'product_support'), ('business', 'business')], default='general_enquiry', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CustomerSupport',
                'verbose_name_plural': 'CustomerSupports',
            },
        ),
    ]
