# Generated by Django 5.2.5 on 2025-09-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_customersupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttobeower',
            name='national_id',
            field=models.FileField(blank=True, null=True, upload_to='national_id_files'),
        ),
    ]
