# Generated by Django 5.2.5 on 2025-09-17 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_requesttobeower_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantpost',
            name='post_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultantpost',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.CreateModel(
            name='ConsultantFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.consultant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ConsultantFollow',
                'verbose_name_plural': 'ConsultantFollows',
                'unique_together': {('user', 'consultant')},
            },
        ),
    ]
