# Generated by Django 5.2.5 on 2025-09-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_consultantpost_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantfollow',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='market.consultant'),
        ),
    ]
