# Generated by Django 5.2.5 on 2025-09-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_remove_order_product_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
