# Generated by Django 5.2.5 on 2025-09-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Percentage or fixed amount', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], default='percent', max_length=10),
        ),
    ]
