# Generated by Django 5.2.5 on 2025-09-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_remove_productdiscount_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('Fixed amount', 'Fixed amount')], default='percent', max_length=20),
        ),
    ]
