# Generated by Django 5.2.5 on 2025-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_alter_productdiscount_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('Fixed', 'Fixed-amount')], default='percent', max_length=20),
        ),
    ]
