# Generated by Django 5.2.5 on 2025-09-27 17:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantpost',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
